### ISSUE TITLE
Add events on media handling

### ISSUE THREAD

**Issue by devgiants** [compagnie-hyperactive/cms#5]
- [ ] download
- [ ] prePersist 
- [ ] postUpdate
- [ ] postLoad
...

**Comment by matthieuleorat** [comment]
For basic action, EasyAdmin already provides events:
Edit:
- EasyAdminEvents::PRE_EDIT
- EasyAdminEvents::POST_EDIT

Show:
- EasyAdminEvents::PRE_SHOW
- EasyAdminEvents::POST_SHOW

New: 
- EasyAdminEvents::PRE_NEW
- EasyAdminEvents::POST_NEW

Delete:
- EasyAdminEvents::PRE_DELETE
- EasyAdminEvents::PRE_REMOVE
- EasyAdminEvents::POST_REMOVE
- EasyAdminEvents::POST_DELETE

Update:
- EasyAdminEvents::PRE_UPDATE
- EasyAdminEvents::POST_UPDATE
- EasyAdminEvents::POST_EDIT

And for the custom download action:
- ImageEvents::PRE_DOWNLOAD
- ImageEvents::POST_DOWNLOAD
